FROM golang:1.24.4-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app/main ./cmd/web/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .
COPY web ./web
COPY assets ./assets
COPY .env.example .env

EXPOSE 8081

CMD ["/app/main"]