version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      API_URL: http://api:8080
    depends_on:
      - api