# Arquivo de configuração do Gemini Code Assist
# Para mais informações, acesse: https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github?hl=pt-br#custom-configuration

# Cofiguração do Gemini Code Assist para projetos em Go
# À partir dos PRs ele revisa o código, sugere melhorias e ajuda na geração de código
# com base nas melhores práticas da linguagem Go.
project_language: Go
have_fun: true
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: true
    summary: true
    code_review: true
ignore_patterns:
  - "**/*_test.go"
  - "**/vendor/**"
  - "**/third_party/**"
  - "go.sum"
  - ".env.example"
  - "LICENSE"
